server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #, http://eureka7002.com:7002/eureka
  instance:
    instance-id: hystrix-dashboard9001
    prefer-ip-address: true
spring:
  application:
    name: consumer-hystrix-dashboard